<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $d4Id = 4;
        $now = now();

        if (! DB::table('form_templates')->where('id', $d4Id)->exists()) {
            return;
        }

        // Row 1 in family table = spouse; rows 2–7 = children 1–6.
        // Date fields use the _dmy derived path (DD/MM/YYYY) auto-generated by canonicalData().
        $mappings = [
            // ── Part I: Main Applicant ───────────────────────────────────────
            ['field_name' => 'PART I Details of the Main Applicant', 'canonical_path' => 'main_applicant.full_name',                        'value_for_truthy' => null],
            ['field_name' => 'undefined',                             'canonical_path' => 'main_applicant.address_residential.full_address', 'value_for_truthy' => null],
            ['field_name' => 'Country of Residence',                  'canonical_path' => 'main_applicant.address_residential.country',      'value_for_truthy' => null],
            ['field_name' => 'Date of Birth',                         'canonical_path' => 'main_applicant.dob_dmy',                          'value_for_truthy' => null],
            ['field_name' => 'Passport Number',                       'canonical_path' => 'main_applicant.passport_1.number',                'value_for_truthy' => null],
            ['field_name' => 'place of issue',                        'canonical_path' => 'main_applicant.passport_1.date_of_issue',         'value_for_truthy' => null],

            // ── Family table row 1: Spouse ────────────────────────────────────
            ['field_name' => 'Full Name_3',      'canonical_path' => 'main_applicant.spouse.full_name',    'value_for_truthy' => null],
            ['field_name' => 'Date of Birth_10', 'canonical_path' => 'main_applicant.spouse.dob_dmy',      'value_for_truthy' => null],
            ['field_name' => 'Relationship_17',  'canonical_path' => 'main_applicant.spouse.relationship', 'value_for_truthy' => null],

            // ── Family table rows 2–7: Children 1–6 ──────────────────────────
            ['field_name' => 'Full Name_4',      'canonical_path' => 'main_applicant.child_1.full_name',    'value_for_truthy' => null],
            ['field_name' => 'Date of Birth_11', 'canonical_path' => 'main_applicant.child_1.dob_dmy',     'value_for_truthy' => null],
            ['field_name' => 'Relationship_18',  'canonical_path' => 'main_applicant.child_1.relationship', 'value_for_truthy' => null],

            ['field_name' => 'Fulla Name_5',     'canonical_path' => 'main_applicant.child_2.full_name',    'value_for_truthy' => null],
            ['field_name' => 'Date of Birth_12', 'canonical_path' => 'main_applicant.child_2.dob_dmy',     'value_for_truthy' => null],
            ['field_name' => 'Relationship_19',  'canonical_path' => 'main_applicant.child_2.relationship', 'value_for_truthy' => null],

            ['field_name' => 'Full Name_6',      'canonical_path' => 'main_applicant.child_3.full_name',    'value_for_truthy' => null],
            ['field_name' => 'Date of Birth_13', 'canonical_path' => 'main_applicant.child_3.dob_dmy',     'value_for_truthy' => null],
            ['field_name' => 'Relationship_20',  'canonical_path' => 'main_applicant.child_3.relationship', 'value_for_truthy' => null],

            ['field_name' => 'Full Name_7',      'canonical_path' => 'main_applicant.child_4.full_name',    'value_for_truthy' => null],
            ['field_name' => 'Date of Birth_14', 'canonical_path' => 'main_applicant.child_4.dob_dmy',     'value_for_truthy' => null],
            ['field_name' => 'Relationship_21',  'canonical_path' => 'main_applicant.child_4.relationship', 'value_for_truthy' => null],

            ['field_name' => 'Full Name_8',      'canonical_path' => 'main_applicant.child_5.full_name',    'value_for_truthy' => null],
            ['field_name' => 'Date of Birth_15', 'canonical_path' => 'main_applicant.child_5.dob_dmy',     'value_for_truthy' => null],
            ['field_name' => 'Relationship_22',  'canonical_path' => 'main_applicant.child_5.relationship', 'value_for_truthy' => null],

            ['field_name' => 'Fulla Name_9',     'canonical_path' => 'main_applicant.child_6.full_name',    'value_for_truthy' => null],
            ['field_name' => 'Date of Birth_16', 'canonical_path' => 'main_applicant.child_6.dob_dmy',     'value_for_truthy' => null],
            ['field_name' => 'Relationship_23',  'canonical_path' => 'main_applicant.child_6.relationship', 'value_for_truthy' => null],

            // ── Signature declaration ─────────────────────────────────────────
            ['field_name' => 'I the undersigned', 'canonical_path' => 'main_applicant.full_name', 'value_for_truthy' => null],
        ];

        foreach ($mappings as $row) {
            DB::table('field_mappings')->upsert(
                array_merge($row, ['form_template_id' => $d4Id, 'created_at' => $now, 'updated_at' => $now]),
                ['form_template_id', 'field_name'],
                ['canonical_path', 'value_for_truthy', 'updated_at'],
            );
        }
    }

    public function down(): void
    {
        DB::table('field_mappings')
            ->where('form_template_id', 4)
            ->delete();
    }
};
