<?php

return [
    'lead_generation_focus' => [
        'name' => 'Lead Generation Focus',
        'description' => 'Optimized for capturing and managing leads from Facebook',
        'icon' => 'Target',
        'color' => 'bg-blue-500',
        'features' => [
            'leadgen' => true,
            'messaging' => true,
            'posts' => false,
            'insights' => true,
            'comments' => false,
        ],
        'webhook_subscriptions' => [
            'leadgen',
            'messages',
            'messaging_postbacks',
            'message_deliveries',
        ],
        'permissions' => [
            'leads_retrieval',
            'pages_show_list',
            'pages_messaging',
            'pages_read_engagement',
        ],
        'benefits' => [
            'Automatic lead capture from Facebook Lead Ads',
            'Real-time lead notifications via webhook',
            'Direct integration with CRM lead pipeline',
            'Messenger integration for lead follow-up',
            'Lead performance analytics and insights',
        ],
    ],

    'social_media_management' => [
        'name' => 'Social Media Management',
        'description' => 'Perfect for managing posts, comments, and engagement',
        'icon' => 'MessageSquare', 
        'color' => 'bg-green-500',
        'features' => [
            'posts' => true,
            'comments' => true,
            'insights' => true,
            'messaging' => false,
            'leadgen' => false,
        ],
        'webhook_subscriptions' => [
            'feed',
            'comments',
            'reactions',
            'mentions',
        ],
        'permissions' => [
            'pages_manage_posts',
            'pages_read_engagement',
            'pages_show_list',
            'read_insights',
        ],
        'benefits' => [
            'Schedule and publish posts directly from CRM',
            'Monitor comments and engagement in real-time',
            'Track post performance and analytics',
            'Respond to comments and mentions',
            'Content planning and engagement insights',
        ],
    ],

    'customer_service_hub' => [
        'name' => 'Customer Service Hub',
        'description' => 'Streamlined for customer support and communication',
        'icon' => 'Users',
        'color' => 'bg-purple-500', 
        'features' => [
            'messaging' => true,
            'comments' => true,
            'posts' => false,
            'insights' => false,
            'leadgen' => false,
        ],
        'webhook_subscriptions' => [
            'messages',
            'messaging_postbacks',
            'message_deliveries',
            'message_reads',
            'comments',
            'mentions',
        ],
        'permissions' => [
            'pages_messaging',
            'pages_messaging_subscriptions',
            'pages_read_engagement',
            'pages_show_list',
        ],
        'benefits' => [
            'Centralized Facebook Messenger conversations',
            'Real-time message notifications',
            'Comment monitoring and responses',
            'Customer support ticket integration',
            'Response time tracking and analytics',
        ],
    ],

    'complete_integration' => [
        'name' => 'Complete Integration',
        'description' => 'Full-featured integration with all Facebook capabilities',
        'icon' => 'Zap',
        'color' => 'bg-orange-500',
        'features' => [
            'leadgen' => true,
            'messaging' => true,
            'posts' => true,
            'comments' => true,
            'insights' => true,
        ],
        'webhook_subscriptions' => [
            'leadgen',
            'messages',
            'messaging_postbacks',
            'message_deliveries',
            'feed',
            'comments',
            'reactions',
            'mentions',
        ],
        'permissions' => [
            'leads_retrieval',
            'pages_messaging',
            'pages_messaging_subscriptions',
            'pages_manage_posts',
            'pages_read_engagement',
            'pages_show_list',
            'read_insights',
        ],
        'benefits' => [
            'Complete Facebook business integration',
            'All lead generation and social features',
            'Full customer communication suite', 
            'Comprehensive analytics and insights',
            'Maximum Facebook marketing capabilities',
        ],
    ],
];