<?php

use App\Enums\Forms\ApplicationStatus;
use App\Enums\Forms\FieldType;
use App\Models\Forms\Application;
use App\Models\Forms\ApplicationGeneration;
use App\Models\Forms\FieldMapping;
use App\Models\Forms\FormTemplate;
use App\Models\Forms\Program;
use App\Models\Forms\TemplateField;
use App\Models\User;

it('program has many form templates', function () {
    $program = Program::factory()->create();
    FormTemplate::factory()->count(3)->create(['program_id' => $program->id]);

    expect($program->formTemplates)->toHaveCount(3);
});

it('form template has many template fields', function () {
    $template = FormTemplate::factory()->create();
    TemplateField::create(['form_template_id' => $template->id, 'field_name' => 'Surname', 'field_type' => FieldType::TEXT]);
    TemplateField::create(['form_template_id' => $template->id, 'field_name' => 'Given Name', 'field_type' => FieldType::TEXT]);

    expect($template->templateFields)->toHaveCount(2);
});

it('form template has many field mappings', function () {
    $template = FormTemplate::factory()->create();
    foreach (['field_a', 'field_b', 'field_c', 'field_d'] as $name) {
        FieldMapping::create(['form_template_id' => $template->id, 'field_name' => $name, 'canonical_path' => "main_applicant.{$name}"]);
    }

    expect($template->fieldMappings)->toHaveCount(4);
});

it('form template active mappings is alias for field mappings', function () {
    $template = FormTemplate::factory()->create();
    foreach (['field_x', 'field_y'] as $name) {
        FieldMapping::create(['form_template_id' => $template->id, 'field_name' => $name, 'canonical_path' => "main_applicant.{$name}"]);
    }

    expect($template->activeMappings)->toHaveCount(2);
});

it('template field belongs to form template', function () {
    $template = FormTemplate::factory()->create();
    $field = TemplateField::create(['form_template_id' => $template->id, 'field_name' => 'Surname', 'field_type' => FieldType::TEXT]);

    expect($field->formTemplate->id)->toBe($template->id);
});

it('field mapping belongs to form template', function () {
    $template = FormTemplate::factory()->create();
    $mapping = FieldMapping::create(['form_template_id' => $template->id, 'field_name' => 'Surname', 'canonical_path' => 'main_applicant.surname']);

    expect($mapping->formTemplate->id)->toBe($template->id);
});

it('program has many applications', function () {
    $program = Program::factory()->create();
    Application::factory()->count(2)->create(['program_id' => $program->id]);

    expect($program->applications)->toHaveCount(2);
});

it('application has many generations', function () {
    $app = Application::factory()->create();
    ApplicationGeneration::factory()->count(3)->create(['application_id' => $app->id]);

    expect($app->generations)->toHaveCount(3);
});

it('application generation belongs to application', function () {
    $app = Application::factory()->create();
    $gen = ApplicationGeneration::factory()->create(['application_id' => $app->id]);

    expect($gen->application->id)->toBe($app->id);
});

it('application belongs to created by user', function () {
    $user = User::factory()->create(['email_verified_at' => now()]);
    $app = Application::factory()->create(['created_by_user_id' => $user->id]);

    expect($app->createdBy->id)->toBe($user->id);
});

it('application generation belongs to generated by user', function () {
    $user = User::factory()->create(['email_verified_at' => now()]);
    $gen = ApplicationGeneration::factory()->create(['generated_by_user_id' => $user->id]);

    expect($gen->generatedBy->id)->toBe($user->id);
});

it('soft deleted application does not appear in default queries', function () {
    $app = Application::factory()->create();
    $appId = $app->id;

    $app->delete();

    expect(Application::find($appId))->toBeNull();
    expect(Application::withTrashed()->find($appId))->not->toBeNull();
});

it('program active templates filters inactive and orders by sort order', function () {
    $program = Program::factory()->create();

    FormTemplate::factory()->create([
        'program_id' => $program->id,
        'is_active' => false,
        'sort_order' => 5,
        'code' => 'inactive-one',
    ]);
    FormTemplate::factory()->create([
        'program_id' => $program->id,
        'is_active' => true,
        'sort_order' => 30,
        'code' => 'active-b',
    ]);
    FormTemplate::factory()->create([
        'program_id' => $program->id,
        'is_active' => true,
        'sort_order' => 10,
        'code' => 'active-a',
    ]);

    $active = $program->activeTemplates;

    expect($active)->toHaveCount(2);
    expect($active->first()->code)->toBe('active-a');
    expect($active->last()->code)->toBe('active-b');
});

it('template field casts json columns to arrays', function () {
    $template = FormTemplate::factory()->create();
    $field = TemplateField::create([
        'form_template_id' => $template->id,
        'field_name' => 'Check Box1',
        'rect_pdf' => [10.0, 20.0, 100.0, 50.0],
        'page_size_pdf' => [612.0, 792.0],
        'export_values' => ['Yes', 'Off'],
        'field_type' => FieldType::CHECKBOX,
    ]);

    expect($field->rect_pdf)->toBeArray()->toHaveCount(4);
    expect($field->page_size_pdf)->toBeArray()->toHaveCount(2);
    expect($field->export_values)->toBeArray()->toContain('Yes');
});

it('application data column casts to array', function () {
    $app = Application::factory()->create([
        'data' => ['main_applicant' => ['passport_number' => 'AB1234567']],
    ]);

    expect($app->fresh()->data)->toBeArray();
    expect($app->fresh()->data['main_applicant']['passport_number'])->toBe('AB1234567');
});

it('application status casts to enum', function () {
    $app = Application::factory()->create(['status' => ApplicationStatus::DRAFT]);

    expect($app->fresh()->status)->toBe(ApplicationStatus::DRAFT);
});
